FROM golang:1.17 as final
RUN apt-get update -y && \
    apt-get install -y build-essential  mingw-w64 gcc-multilib gcc-mingw-w64  automake 

# Get dependancies - will also be cached if we won't change mod/sum
WORKDIR /go/src/project/vss
COPY go.mod .
COPY go.sum .
RUN go mod download

# Load Scanner
COPY / /go/src/project/vss/

# Compile for Windows64
RUN CGO_ENABLED="1" \
    GOARCH="386"\
    GOOS="windows"\
    CC="i686-w64-mingw32-gcc"\
    go build -o /go/bin/vss.exe cmd/example/*